name: Build LaTeX document

on:
  push:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    
    - name: Install fonts and required packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          fonts-noto-cjk \
          fonts-noto-cjk-extra \
          fonts-nanum \
          texlive-xetex \
          texlive-lang-korean \
          texlive-fonts-recommended \
          texlive-fonts-extra \
          latexmk
        
    - name: Prepare font directory and update font cache
      run: |
        mkdir -p "$HOME/.fonts"
        sudo fc-cache -fv

    - name: Compile LaTeX document with XeLaTeX
      run: |
        latexmk -xelatex -interaction=nonstopmode -file-line-error main.tex
      continue-on-error: true
      id: compile

    - name: Check compilation error
      if: steps.compile.outcome == 'failure'
      run: |
        echo "XeLaTeX 문서 컴파일 중 오류가 발생했습니다." >> error.log
        cat error.log
        exit 1

    - name: Upload PDF file
      if: steps.compile.outcome == 'success'
      uses: actions/upload-artifact@v3
      with:
        name: PDF
        path: main.pdf

    - name: Upload error log
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: error-log
        path: error.log
