name: Build LaTeX document

on:
  push:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Check environment and install fonts
      run: |
        echo "OS: $(uname -s)"
        echo "Distribution: $(lsb_release -d)"
        echo "현재 설치된 폰트 관련 패키지:"
        dpkg -l | grep font
        
        echo "한국어와 영어를 지원하는 폰트 설치"
        sudo apt-get update
        sudo apt-get install -y fonts-noto-cjk fonts-noto-cjk-extra fonts-noto fonts-nanum
        
        if [ $? -ne 0 ]; then
          echo "폰트 설치 중 오류가 발생했습니다." >> error.log
          exit 1
        fi
        
        echo "설치 후 폰트 관련 패키지:"
        dpkg -l | grep font

    - name: Prepare font directory
      run: |
        mkdir -p "$HOME/.fonts"
        if [ ! -w "$HOME/.fonts" ]; then
          echo "권한 문제가 발생했습니다. 권한을 변경합니다."
          sudo chown -R $(whoami):$(whoami) "$HOME/.fonts"
          if [ $? -ne 0 ]; then
            echo "폰트 디렉토리 권한 변경 중 오류가 발생했습니다." >> error.log
            exit 1
          fi
        fi

    - name: Update font cache
      run: |
        fc-cache -fv
        if [ $? -ne 0 ]; then
          echo "폰트 캐시 업데이트 중 오류가 발생했습니다." >> error.log
          exit 1
        fi

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        extra_system_packages: "ko ko-x11 cm-super"
      continue-on-error: true
      id: compile

    - name: Check compilation result
      if: steps.compile.outcome == 'failure'
      run: |
        echo "LaTeX 문서 컴파일 중 오류가 발생했습니다." >> error.log
        exit 1

    - name: Upload PDF file
      if: steps.compile.outcome == 'success'
      uses: actions/upload-artifact@v2
      with:
        name: PDF
        path: main.pdf

    - name: Upload error log
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: error-log
        path: error.log
